name: calendar_datetime_extension
description: "A dart package that extends some date time utilities from Jiffy."
version: 1.0.2
homepage: https://github.com/rafdls/calendar_datetime_extension

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  jiffy: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
